apiVersion: v1
kind: Service
metadata:
  name: nginx-project-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx-project-label
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007