apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  labels:
    app: app2-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2-deploy
  template:
    metadata:
      labels:
        app: app2-deploy
    spec:
      containers:
      - name: app2-deploy-container
        image: scor32k/app2-image:v1
        ports:
        - containerPort: 3000 
