# Stage 1
FROM node:20-alpine3.17 as react-build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

# Stage 2
FROM nginx

COPY --from=react-build /app/dist /usr/share/nginx/html
